'use strict'

// node --print-bytecode 1-index.js

let v = 10;
let a = v + 7;
console.log('Hello ' + a);

/*

 3388 S> 0xaa79bf21ae5 @   15 : 0f                LdaNull
 3400 S> 0xaa79bf21ae6 @   16 : a9                Return
 3410 S> 0xaa79bf21ae7 @   17 : 2d 02 00 06       GetNamedProperty <this>, [0], [6]
         0xaa79bf21aeb @   21 : c3                Star1
 3420 E> 0xaa79bf21aec @   22 : 2d 02 01 08       GetNamedProperty <this>, [1], [8]
         0xaa79bf21af0 @   26 : c2                Star2
         0xaa79bf21af1 @   27 : 0e                LdaUndefined
 3428 E> 0xaa79bf21af2 @   28 : 34 f9 f8 0a       SetKeyedProperty r1, r2, [10]
 3465 S> 0xaa79bf21af6 @   32 : 2d 02 01 0e       GetNamedProperty <this>, [1], [14]
 3472 E> 0xaa79bf21afa @   36 : 44 01 0d          AddSmi [1], [13]
         0xaa79bf21afd @   39 : c2                Star2
         0xaa79bf21afe @   40 : 17 04             LdaImmutableCurrentContextSlot [4]
 3479 E> 0xaa79bf21b00 @   42 : aa 02             ThrowReferenceErrorIfHole [2]
 3477 E> 0xaa79bf21b02 @   44 : 40 f8 0c          BitwiseAnd r2, [12]
 3457 E> 0xaa79bf21b05 @   47 : 32 02 01 10       SetNamedProperty <this>, [1], [16]
 3490 S> 0xaa79bf21b09 @   51 : 0b fa             Ldar r0
 3506 S> 0xaa79bf21b0b @   53 : a9                Return
Constant pool (size = 3)
0xaa79bf21a79: [FixedArray] in OldSpace
 - map: 0x3fc2dc0012d9 <Map(FIXED_ARRAY_TYPE)>
 - length: 3
           0: 0x3fc2dc005fe9 <String[4]: #list>
           1: 0x04e986dca0a1 <String[6]: #bottom>
           2: 0x04e986dca111 <String[5]: #kMask>
Handler Table (size = 0)
Source Position Table (size = 38)
0x0aa79bf21b11 <ByteArray[38]>
[generated bytecode for function: emitBeforeScript (0x16e16e0aec91 <SharedFunctionInfo emitBeforeScript>)]
Bytecode length: 42
Parameter count 4
Register count 4
Frame size 32
Bytecode age: 0
16953 S> 0xaa79bf21c0e @    0 : 17 47             LdaImmutableCurrentContextSlot [71]
         0xaa79bf21c10 @    2 : c4                Star0
         0xaa79bf21c11 @    3 : 19 03 f9          Mov a0, r1
         0xaa79bf21c14 @    6 : 19 04 f8          Mov a1, r2
         0xaa79bf21c17 @    9 : 19 05 f7          Mov a2, r3
16953 E> 0xaa79bf21c1a @   12 : 60 fa f9 03 00    CallUndefinedReceiver r0, r1-r3, [0]
17009 S> 0xaa79bf21c1f @   17 : 17 40             LdaImmutableCurrentContextSlot [64]
         0xaa79bf21c21 @   19 : c4                Star0
         0xaa79bf21c22 @   20 : 17 16             LdaImmutableCurrentContextSlot [22]
17022 E> 0xaa79bf21c24 @   22 : aa 00             ThrowReferenceErrorIfHole [0]
         0xaa79bf21c26 @   24 : c3                Star1
17013 E> 0xaa79bf21c27 @   25 : 62 fa f9 02       CallUndefinedReceiver1 r0, r1, [2]
         0xaa79bf21c2b @   29 : 97 0b             JumpIfToBooleanFalse [11] (0xaa79bf21c36 @ 40)
17036 S> 0xaa79bf21c2d @   31 : 17 25             LdaImmutableCurrentContextSlot [37]
         0xaa79bf21c2f @   33 : aa 01             ThrowReferenceErrorIfHole [1]
         0xaa79bf21c31 @   35 : c4                Star0
17036 E> 0xaa79bf21c32 @   36 : 62 fa 03 04       CallUndefinedReceiver1 r0, a0, [4]
         0xaa79bf21c36 @   40 : 0e                LdaUndefined
17063 S> 0xaa79bf21c37 @   41 : a9                Return
Constant pool (size = 2)
0xaa79bf21bb9: [FixedArray] in OldSpace
 - map: 0x3fc2dc0012d9 <Map(FIXED_ARRAY_TYPE)>
 - length: 2
           0: 0x04e986dc3cc1 <String[7]: #kBefore>
           1: 0x04e986dc3e41 <String[16]: #emitBeforeNative>
Handler Table (size = 0)
Source Position Table (size = 22)
0x0aa79bf21c39 <ByteArray[22]>
[generated bytecode for function: pushAsyncContext (0x16e16e0aedd1 <SharedFunctionInfo pushAsyncContext>)]
Bytecode length: 180
Parameter count 4
Register count 4
Frame size 32
Bytecode age: 0
17612 S> 0xaa79bf21d5e @    0 : 17 0b             LdaImmutableCurrentContextSlot [11]
         0xaa79bf21d60 @    2 : aa 00             ThrowReferenceErrorIfHole [0]
         0xaa79bf21d62 @    4 : c3                Star1
         0xaa79bf21d63 @    5 : 17 1f             LdaImmutableCurrentContextSlot [31]
17630 E> 0xaa79bf21d65 @    7 : aa 01             ThrowReferenceErrorIfHole [1]
17629 E> 0xaa79bf21d67 @    9 : 2f f9 00          GetKeyedProperty r1, [0]
         0xaa79bf21d6a @   12 : c4                Star0
17647 S> 0xaa79bf21d6b @   13 : 17 0d             LdaImmutableCurrentContextSlot [13]
         0xaa79bf21d6d @   15 : aa 02             ThrowReferenceErrorIfHole [2]
         0xaa79bf21d6f @   17 : c3                Star1
         0xaa79bf21d70 @   18 : 0b 05             Ldar a2
17681 E> 0xaa79bf21d72 @   20 : 34 f9 fa 02       SetKeyedProperty r1, r0, [2]
17695 S> 0xaa79bf21d76 @   24 : 0b fa             Ldar r0
17706 E> 0xaa79bf21d78 @   26 : 46 02 04          MulSmi [2], [4]
         0xaa79bf21d7b @   29 : c3                Star1
         0xaa79bf21d7c @   30 : 17 09             LdaImmutableCurrentContextSlot [9]
17713 E> 0xaa79bf21d7e @   32 : aa 03             ThrowReferenceErrorIfHole [3]
         0xaa79bf21d80 @   34 : c2                Star2
17724 E> 0xaa79bf21d81 @   35 : 2d f8 04 05       GetNamedProperty r2, [4], [5]
         0xaa79bf21d85 @   39 : c2                Star2
17740 E> 0xaa79bf21d86 @   40 : 2d f8 05 07       GetNamedProperty r2, [5], [7]
17710 E> 0xaa79bf21d8a @   44 : 70 f9 09          TestGreaterThanOrEqual r1, [9]
         0xaa79bf21d8d @   47 : 99 0d             JumpIfFalse [13] (0xaa79bf21d9a @ 60)
17752 S> 0xaa79bf21d8f @   49 : 17 0e             LdaImmutableCurrentContextSlot [14]
         0xaa79bf21d91 @   51 : aa 06             ThrowReferenceErrorIfHole [6]
         0xaa79bf21d93 @   53 : c3                Star1
17759 E> 0xaa79bf21d94 @   54 : 63 f9 03 04 0a    CallUndefinedReceiver2 r1, a0, a1, [10]
17802 S> 0xaa79bf21d99 @   59 : a9                Return
17805 S> 0xaa79bf21d9a @   60 : 17 09             LdaImmutableCurrentContextSlot [9]
         0xaa79bf21d9c @   62 : aa 03             ThrowReferenceErrorIfHole [3]
         0xaa79bf21d9e @   64 : c3                Star1
17816 E> 0xaa79bf21d9f @   65 : 2d f9 04 05       GetNamedProperty r1, [4], [5]
         0xaa79bf21da3 @   69 : c3                Star1
         0xaa79bf21da4 @   70 : 0b fa             Ldar r0
17839 E> 0xaa79bf21da6 @   72 : 46 02 0c          MulSmi [2], [12]
         0xaa79bf21da9 @   75 : c2                Star2
         0xaa79bf21daa @   76 : 17 0c             LdaImmutableCurrentContextSlot [12]
17846 E> 0xaa79bf21dac @   78 : aa 07             ThrowReferenceErrorIfHole [7]
         0xaa79bf21dae @   80 : c1                Star3
         0xaa79bf21daf @   81 : 17 1b             LdaImmutableCurrentContextSlot [27]
17862 E> 0xaa79bf21db1 @   83 : aa 08             ThrowReferenceErrorIfHole [8]
17861 E> 0xaa79bf21db3 @   85 : 2f f7 0d          GetKeyedProperty r3, [13]
17844 E> 0xaa79bf21db6 @   88 : 34 f9 f8 0f       SetKeyedProperty r1, r2, [15]
17884 S> 0xaa79bf21dba @   92 : 17 09             LdaImmutableCurrentContextSlot [9]
         0xaa79bf21dbc @   94 : aa 03             ThrowReferenceErrorIfHole [3]
         0xaa79bf21dbe @   96 : c3                Star1
17895 E> 0xaa79bf21dbf @   97 : 2d f9 04 05       GetNamedProperty r1, [4], [5]
         0xaa79bf21dc3 @  101 : c3                Star1
         0xaa79bf21dc4 @  102 : 0b fa             Ldar r0
17918 E> 0xaa79bf21dc6 @  104 : 46 02 12          MulSmi [2], [18]
17922 E> 0xaa79bf21dc9 @  107 : 44 01 11          AddSmi [1], [17]
         0xaa79bf21dcc @  110 : c2                Star2
         0xaa79bf21dcd @  111 : 17 0c             LdaImmutableCurrentContextSlot [12]
17929 E> 0xaa79bf21dcf @  113 : aa 07             ThrowReferenceErrorIfHole [7]
         0xaa79bf21dd1 @  115 : c1                Star3
         0xaa79bf21dd2 @  116 : 17 1d             LdaImmutableCurrentContextSlot [29]
17945 E> 0xaa79bf21dd4 @  118 : aa 09             ThrowReferenceErrorIfHole [9]
17944 E> 0xaa79bf21dd6 @  120 : 2f f7 13          GetKeyedProperty r3, [19]
17927 E> 0xaa79bf21dd9 @  123 : 34 f9 f8 15       SetKeyedProperty r1, r2, [21]
17965 S> 0xaa79bf21ddd @  127 : 17 0b             LdaImmutableCurrentContextSlot [11]
         0xaa79bf21ddf @  129 : aa 00             ThrowReferenceErrorIfHole [0]
         0xaa79bf21de1 @  131 : c3                Star1
         0xaa79bf21de2 @  132 : 17 1f             LdaImmutableCurrentContextSlot [31]
17983 E> 0xaa79bf21de4 @  134 : aa 01             ThrowReferenceErrorIfHole [1]
         0xaa79bf21de6 @  136 : c2                Star2
         0xaa79bf21de7 @  137 : 2f f9 17          GetKeyedProperty r1, [23]
         0xaa79bf21dea @  140 : 50 19             Inc [25]
17996 E> 0xaa79bf21dec @  142 : 34 f9 f8 1a       SetKeyedProperty r1, r2, [26]
18002 S> 0xaa79bf21df0 @  146 : 17 0c             LdaImmutableCurrentContextSlot [12]
         0xaa79bf21df2 @  148 : aa 07             ThrowReferenceErrorIfHole [7]
         0xaa79bf21df4 @  150 : c3                Star1
         0xaa79bf21df5 @  151 : 17 1b             LdaImmutableCurrentContextSlot [27]
18018 E> 0xaa79bf21df7 @  153 : aa 08             ThrowReferenceErrorIfHole [8]
         0xaa79bf21df9 @  155 : c2                Star2
         0xaa79bf21dfa @  156 : 0b 03             Ldar a0
18037 E> 0xaa79bf21dfc @  158 : 34 f9 f8 1c       SetKeyedProperty r1, r2, [28]
18050 S> 0xaa79bf21e00 @  162 : 17 0c             LdaImmutableCurrentContextSlot [12]
         0xaa79bf21e02 @  164 : aa 07             ThrowReferenceErrorIfHole [7]
         0xaa79bf21e04 @  166 : c3                Star1
         0xaa79bf21e05 @  167 : 17 1d             LdaImmutableCurrentContextSlot [29]
18066 E> 0xaa79bf21e07 @  169 : aa 09             ThrowReferenceErrorIfHole [9]
         0xaa79bf21e09 @  171 : c2                Star2
         0xaa79bf21e0a @  172 : 0b 04             Ldar a1
18083 E> 0xaa79bf21e0c @  174 : 34 f9 f8 1e       SetKeyedProperty r1, r2, [30]
         0xaa79bf21e10 @  178 : 0e                LdaUndefined
18101 S> 0xaa79bf21e11 @  179 : a9                Return
Constant pool (size = 10)
0xaa79bf21cc9: [FixedArray] in OldSpace
 - map: 0x3fc2dc0012d9 <Map(FIXED_ARRAY_TYPE)>
 - length: 10
           0: 0x04e986dc3b39 <String[17]: #async_hook_fields>
           1: 0x04e986dc3dd1 <String[12]: #kStackLength>
           2: 0x04e986dc3b81 <String[25]: #execution_async_resources>
           3: 0x04e986dc3af1 <String[10]: #async_wrap>
           4: 0x04e986dd1de1 <String[15]: #async_ids_stack>
           5: 0x3fc2dc0078d1 <String[6]: #length>
           6: 0x04e986dc3bb1 <String[17]: #pushAsyncContext_>
           7: 0x04e986dc3b61 <String[15]: #async_id_fields>
           8: 0x04e986dc3d41 <String[17]: #kExecutionAsyncId>
           9: 0x04e986dc3d89 <String[15]: #kTriggerAsyncId>
Handler Table (size = 0)
Source Position Table (size = 88)
0x0aa79bf21e19 <ByteArray[88]>
[generated bytecode for function: afterWriteTick (0x358ffa86f709 <SharedFunctionInfo afterWriteTick>)]
Bytecode length: 46
Parameter count 2
Register count 9
Frame size 72
Bytecode age: 0
15114 E> 0xaa79bf21f66 @    0 : 2d 03 00 00       GetNamedProperty a0, [0], [0]
         0xaa79bf21f6a @    4 : c4                Star0
15122 E> 0xaa79bf21f6b @    5 : 2d 03 01 02       GetNamedProperty a0, [1], [2]
         0xaa79bf21f6f @    9 : c3                Star1
15129 E> 0xaa79bf21f70 @   10 : 2d 03 02 04       GetNamedProperty a0, [2], [4]
         0xaa79bf21f74 @   14 : c2                Star2
15136 E> 0xaa79bf21f75 @   15 : 2d 03 03 06       GetNamedProperty a0, [3], [6]
         0xaa79bf21f79 @   19 : c1                Star3
15146 S> 0xaa79bf21f7a @   20 : 0f                LdaNull
15171 E> 0xaa79bf21f7b @   21 : 32 f9 04 08       SetNamedProperty r1, [4], [8]
15181 S> 0xaa79bf21f7f @   25 : 17 23             LdaImmutableCurrentContextSlot [35]
         0xaa79bf21f81 @   27 : c0                Star4
         0xaa79bf21f82 @   28 : 19 fa f5          Mov r0, r5
         0xaa79bf21f85 @   31 : 19 f9 f4          Mov r1, r6
         0xaa79bf21f88 @   34 : 19 f8 f3          Mov r2, r7
         0xaa79bf21f8b @   37 : 19 f7 f2          Mov r3, r8
15188 E> 0xaa79bf21f8e @   40 : 60 f6 f5 04 0a    CallUndefinedReceiver r4, r5-r8, [10]
15225 S> 0xaa79bf21f93 @   45 : a9                Return
Constant pool (size = 5)
0xaa79bf21ef9: [FixedArray] in OldSpace
 - map: 0x3fc2dc0012d9 <Map(FIXED_ARRAY_TYPE)>
 - length: 5
           0: 0x188e9f02d529 <String[6]: #stream>
           1: 0x04e986dd3179 <String[5]: #state>
           2: 0x04e986dc7679 <String[5]: #count>
           3: 0x04e986dc6ea1 <String[2]: #cb>
           4: 0x0aa79bf0c551 <String[18]: #afterWriteTickInfo>
Handler Table (size = 0)
Source Position Table (size = 23)
0x0aa79bf21f99 <ByteArray[23]>
[generated bytecode for function: afterWrite (0x358ffa86f759 <SharedFunctionInfo afterWrite>)]
Bytecode length: 108
Parameter count 5
Register count 4
Frame size 32
Bytecode age: 0
15304 S> 0xaa79bf220be @    0 : 2d 04 00 00       GetNamedProperty a1, [0], [0]
         0xaa79bf220c2 @    4 : 54                ToBooleanLogicalNot
         0xaa79bf220c3 @    5 : 99 18             JumpIfFalse [24] (0xaa79bf220db @ 29)
15322 E> 0xaa79bf220c5 @    7 : 2d 03 01 02       GetNamedProperty a0, [1], [2]
         0xaa79bf220c9 @   11 : 54                ToBooleanLogicalNot
         0xaa79bf220ca @   12 : 99 11             JumpIfFalse [17] (0xaa79bf220db @ 29)
15341 E> 0xaa79bf220cc @   14 : 2d 04 02 04       GetNamedProperty a1, [2], [4]
         0xaa79bf220d0 @   18 : c3                Star1
         0xaa79bf220d1 @   19 : 0c                LdaZero
15348 E> 0xaa79bf220d2 @   20 : 6c f9 06          TestEqualStrict r1, [6]
         0xaa79bf220d5 @   23 : 99 06             JumpIfFalse [6] (0xaa79bf220db @ 29)
15367 E> 0xaa79bf220d7 @   25 : 2d 04 03 07       GetNamedProperty a1, [3], [7]
         0xaa79bf220db @   29 : c4                Star0
15380 S> 0xaa79bf220dc @   30 : 97 14             JumpIfToBooleanFalse [20] (0xaa79bf220f0 @ 50)
15401 S> 0xaa79bf220de @   32 : 12                LdaFalse
15417 E> 0xaa79bf220df @   33 : 32 04 03 09       SetNamedProperty a1, [3], [9]
15437 S> 0xaa79bf220e3 @   37 : 2d 03 04 0b       GetNamedProperty a0, [4], [11]
         0xaa79bf220e7 @   41 : c3                Star1
         0xaa79bf220e8 @   42 : 13 05             LdaConstant [5]
         0xaa79bf220ea @   44 : c1                Star3
15437 E> 0xaa79bf220eb @   45 : 5e f9 03 f7 0d    CallProperty1 r1, a0, r3, [13]
15474 S> 0xaa79bf220f0 @   50 : 0b 05             Ldar a2
         0xaa79bf220f2 @   52 : 75 0f             ToNumeric [15]
         0xaa79bf220f4 @   54 : c3                Star1
         0xaa79bf220f5 @   55 : 51 0f             Dec [15]
         0xaa79bf220f7 @   57 : 18 05             Star a2
         0xaa79bf220f9 @   59 : 0c                LdaZero
15474 E> 0xaa79bf220fa @   60 : 6e f9 10          TestGreaterThan r1, [16]
         0xaa79bf220fd @   63 : 99 16             JumpIfFalse [22] (0xaa79bf22113 @ 85)
15485 S> 0xaa79bf220ff @   65 : 2d 04 06 11       GetNamedProperty a1, [6], [17]
         0xaa79bf22103 @   69 : 51 13             Dec [19]
15500 E> 0xaa79bf22105 @   71 : 32 04 06 14       SetNamedProperty a1, [6], [20]
15508 S> 0xaa79bf22109 @   75 : 0f                LdaNull
         0xaa79bf2210a @   76 : c2                Star2
15508 E> 0xaa79bf2210b @   77 : 62 06 f8 16       CallUndefinedReceiver1 a3, r2, [22]
15459 E> 0xaa79bf2210f @   81 : 89 1f 00 18       JumpLoop [31], [0], [24] (0xaa79bf220f0 @ 50)
15535 S> 0xaa79bf22113 @   85 : 2d 04 01 19       GetNamedProperty a1, [1], [25]
         0xaa79bf22117 @   89 : 97 09             JumpIfToBooleanFalse [9] (0xaa79bf22120 @ 98)
15552 S> 0xaa79bf22119 @   91 : 17 24             LdaImmutableCurrentContextSlot [36]
         0xaa79bf2211b @   93 : c3                Star1
15552 E> 0xaa79bf2211c @   94 : 62 f9 04 1b       CallUndefinedReceiver1 r1, a1, [27]
15579 S> 0xaa79bf22120 @   98 : 17 29             LdaImmutableCurrentContextSlot [41]
         0xaa79bf22122 @  100 : c3                Star1
15579 E> 0xaa79bf22123 @  101 : 63 f9 03 04 1d    CallUndefinedReceiver2 r1, a0, a1, [29]
         0xaa79bf22128 @  106 : 0e                LdaUndefined
15607 S> 0xaa79bf22129 @  107 : a9                Return
Constant pool (size = 7)
0xaa79bf22041: [FixedArray] in OldSpace
 - map: 0x3fc2dc0012d9 <Map(FIXED_ARRAY_TYPE)>
 - length: 7
           0: 0x0aa79bf099b1 <String[6]: #ending>
           1: 0x04e986dd2131 <String[9]: #destroyed>
           2: 0x3fc2dc0078d1 <String[6]: #length>
           3: 0x358ffa86ecc1 <String[9]: #needDrain>
           4: 0x04e986dc74d1 <String[4]: #emit>
           5: 0x0aa79bf21fd9 <String[5]: #drain>
           6: 0x0aa79bf0c579 <String[9]: #pendingcb>
Handler Table (size = 0)
Source Position Table (size = 54)
0x0aa79bf22131 <ByteArray[54]>
[generated bytecode for function: get (0x358ffa8643e9 <SharedFunctionInfo get>)]
Bytecode length: 35
Parameter count 1
Register count 1
Frame size 8
Bytecode age: 0
 3834 S> 0xaa79bf2224e @    0 : 2d 02 00 00       GetNamedProperty <this>, [0], [0]
         0xaa79bf22252 @    4 : 9c 08             JumpIfUndefined [8] (0xaa79bf2225a @ 12)
 3879 E> 0xaa79bf22254 @    6 : 2d 02 01 02       GetNamedProperty <this>, [1], [2]
         0xaa79bf22258 @   10 : 9d 04             JumpIfNotUndefined [4] (0xaa79bf2225c @ 14)
 3919 S> 0xaa79bf2225a @   12 : 12                LdaFalse
 3932 S> 0xaa79bf2225b @   13 : a9                Return
 3959 S> 0xaa79bf2225c @   14 : 2d 02 00 04       GetNamedProperty <this>, [0], [4]
         0xaa79bf22260 @   18 : c4                Star0
 3974 E> 0xaa79bf22261 @   19 : 2d fa 02 06       GetNamedProperty r0, [2], [6]
         0xaa79bf22265 @   23 : 97 0b             JumpIfToBooleanFalse [11] (0xaa79bf22270 @ 34)
 3992 E> 0xaa79bf22267 @   25 : 2d 02 01 08       GetNamedProperty <this>, [1], [8]
         0xaa79bf2226b @   29 : c4                Star0
 4007 E> 0xaa79bf2226c @   30 : 2d fa 02 0a       GetNamedProperty r0, [2], [10]
 4017 S> 0xaa79bf22270 @   34 : a9                Return
Constant pool (size = 3)
0xaa79bf221f1: [FixedArray] in OldSpace
 - map: 0x3fc2dc0012d9 <Map(FIXED_ARRAY_TYPE)>
 - length: 3
           0: 0x0aa79bf09971 <String[14]: #_readableState>
           1: 0x188e9f02d541 <String[14]: #_writableState>
           2: 0x04e986dd2131 <String[9]: #destroyed>
Handler Table (size = 0)
Source Position Table (size = 23)
0x0aa79bf22279 <ByteArray[23]>
[generated bytecode for function:  (0x188e9f02d5f1 <SharedFunctionInfo>)]
Bytecode length: 87
Parameter count 2
Register count 5
Frame size 40
Bytecode age: 0
10905 S> 0xaa79bf2238e @    0 : 17 02             LdaImmutableCurrentContextSlot [2]
         0xaa79bf22390 @    2 : c3                Star1
         0xaa79bf22391 @    3 : 15 ff 49 01       LdaImmutableContextSlot <context>, [73], [1]
10922 E> 0xaa79bf22395 @    7 : aa 00             ThrowReferenceErrorIfHole [0]
10918 E> 0xaa79bf22397 @    9 : 6c f9 00          TestEqualStrict r1, [0]
         0xaa79bf2239a @   12 : 99 0b             JumpIfFalse [11] (0xaa79bf223a5 @ 23)
         0xaa79bf2239c @   14 : 17 03             LdaImmutableCurrentContextSlot [3]
         0xaa79bf2239e @   16 : c3                Star1
10950 E> 0xaa79bf2239f @   17 : 2d f9 01 01       GetNamedProperty r1, [1], [1]
         0xaa79bf223a3 @   21 : 8a 09             Jump [9] (0xaa79bf223ac @ 30)
         0xaa79bf223a5 @   23 : 17 03             LdaImmutableCurrentContextSlot [3]
         0xaa79bf223a7 @   25 : c3                Star1
10969 E> 0xaa79bf223a8 @   26 : 2d f9 02 03       GetNamedProperty r1, [2], [3]
         0xaa79bf223ac @   30 : c4                Star0
10982 S> 0xaa79bf223ad @   31 : 0b 03             Ldar a0
         0xaa79bf223af @   33 : 9a 34             JumpIfNull [52] (0xaa79bf223e3 @ 85)
11010 E> 0xaa79bf223b1 @   35 : 2d fa 03 05       GetNamedProperty r0, [3], [5]
         0xaa79bf223b5 @   39 : c3                Star1
11025 E> 0xaa79bf223b6 @   40 : 2d f9 04 07       GetNamedProperty r1, [4], [7]
         0xaa79bf223ba @   44 : 96 29             JumpIfToBooleanTrue [41] (0xaa79bf223e3 @ 85)
11421 S> 0xaa79bf223bc @   46 : 2d fa 05 09       GetNamedProperty r0, [5], [9]
         0xaa79bf223c0 @   50 : c3                Star1
         0xaa79bf223c1 @   51 : 13 06             LdaConstant [6]
         0xaa79bf223c3 @   53 : c1                Star3
11421 E> 0xaa79bf223c4 @   54 : 5e f9 fa f7 0b    CallProperty1 r1, r0, r3, [11]
         0xaa79bf223c9 @   59 : c3                Star1
         0xaa79bf223ca @   60 : 0c                LdaZero
11444 E> 0xaa79bf223cb @   61 : 6c f9 0d          TestEqualStrict r1, [13]
         0xaa79bf223ce @   64 : 99 15             JumpIfFalse [21] (0xaa79bf223e3 @ 85)
11468 S> 0xaa79bf223d0 @   66 : 2d fa 07 0e       GetNamedProperty r0, [7], [14]
         0xaa79bf223d4 @   70 : c3                Star1
         0xaa79bf223d5 @   71 : 13 06             LdaConstant [6]
         0xaa79bf223d7 @   73 : c1                Star3
         0xaa79bf223d8 @   74 : 15 ff 59 01       LdaImmutableContextSlot <context>, [89], [1]
         0xaa79bf223dc @   78 : c0                Star4
11468 E> 0xaa79bf223dd @   79 : 5f f9 fa f7 f6 10 CallProperty2 r1, r0, r3, r4, [16]
         0xaa79bf223e3 @   85 : 0e                LdaUndefined
11505 S> 0xaa79bf223e4 @   86 : a9                Return
Constant pool (size = 8)
0xaa79bf22309: [FixedArray] in OldSpace
 - map: 0x3fc2dc0012d9 <Map(FIXED_ARRAY_TYPE)>
 - length: 8
           0: 0x04e986dcaf39 <String[10]: #kUseStdout>
           1: 0x188e9f02c731 <String[7]: #_stdout>
           2: 0x188e9f02c749 <String[7]: #_stderr>
           3: 0x188e9f02d541 <String[14]: #_writableState>
           4: 0x188e9f02d561 <String[12]: #errorEmitted>
           5: 0x04e986dc72a1 <String[13]: #listenerCount>
           6: 0x04e986dc6da9 <String[5]: #error>
           7: 0x04e986dc5079 <String[4]: #once>
Handler Table (size = 0)
Source Position Table (size = 36)
0x0aa79bf223e9 <ByteArray[36]>
[generated bytecode for function: finishMaybe (0x358ffa86f961 <SharedFunctionInfo finishMaybe>)]
Bytecode length: 97
Parameter count 4
Register count 5
Frame size 40
Bytecode age: 0
21091 S> 0xaa79bf2253e @    0 : 17 26             LdaImmutableCurrentContextSlot [38]
         0xaa79bf22540 @    2 : c4                Star0
21095 E> 0xaa79bf22541 @    3 : 62 fa 04 00       CallUndefinedReceiver1 r0, a1, [0]
         0xaa79bf22545 @    7 : 97 58             JumpIfToBooleanFalse [88] (0xaa79bf2259d @ 95)
21120 S> 0xaa79bf22547 @    9 : 17 28             LdaImmutableCurrentContextSlot [40]
         0xaa79bf22549 @   11 : c4                Star0
21120 E> 0xaa79bf2254a @   12 : 63 fa 03 04 02    CallUndefinedReceiver2 r0, a0, a1, [2]
21160 S> 0xaa79bf2254f @   17 : 2d 04 00 04       GetNamedProperty a1, [0], [4]
         0xaa79bf22553 @   21 : c4                Star0
         0xaa79bf22554 @   22 : 0c                LdaZero
21170 E> 0xaa79bf22555 @   23 : 6c fa 06          TestEqualStrict r0, [6]
         0xaa79bf22558 @   26 : 99 45             JumpIfFalse [69] (0xaa79bf2259d @ 95)
21185 S> 0xaa79bf2255a @   28 : 0b 05             Ldar a2
         0xaa79bf2255c @   30 : 97 26             JumpIfToBooleanFalse [38] (0xaa79bf22582 @ 68)
21205 S> 0xaa79bf2255e @   32 : 2d 04 00 04       GetNamedProperty a1, [0], [4]
         0xaa79bf22562 @   36 : 50 07             Inc [7]
21220 E> 0xaa79bf22564 @   38 : 32 04 00 08       SetNamedProperty a1, [0], [8]
21232 S> 0xaa79bf22568 @   42 : 17 02             LdaImmutableCurrentContextSlot [2]
         0xaa79bf2256a @   44 : c3                Star1
21240 E> 0xaa79bf2256b @   45 : 2d f9 01 0a       GetNamedProperty r1, [1], [10]
         0xaa79bf2256f @   49 : c4                Star0
         0xaa79bf22570 @   50 : 80 02 00 02       CreateClosure [2], [0], #2
         0xaa79bf22574 @   54 : c2                Star2
         0xaa79bf22575 @   55 : 19 03 f7          Mov a0, r3
         0xaa79bf22578 @   58 : 19 04 f6          Mov a1, r4
21240 E> 0xaa79bf2257b @   61 : 5c fa f9 04 0c    CallProperty r0, r1-r4, [12]
         0xaa79bf22580 @   66 : 8a 1d             Jump [29] (0xaa79bf2259d @ 95)
21442 S> 0xaa79bf22582 @   68 : 17 26             LdaImmutableCurrentContextSlot [38]
         0xaa79bf22584 @   70 : c4                Star0
21446 E> 0xaa79bf22585 @   71 : 62 fa 04 0e       CallUndefinedReceiver1 r0, a1, [14]
         0xaa79bf22589 @   75 : 97 14             JumpIfToBooleanFalse [20] (0xaa79bf2259d @ 95)
21475 S> 0xaa79bf2258b @   77 : 2d 04 00 04       GetNamedProperty a1, [0], [4]
         0xaa79bf2258f @   81 : 50 10             Inc [16]
21490 E> 0xaa79bf22591 @   83 : 32 04 00 08       SetNamedProperty a1, [0], [8]
21502 S> 0xaa79bf22595 @   87 : 17 2a             LdaImmutableCurrentContextSlot [42]
         0xaa79bf22597 @   89 : c4                Star0
21502 E> 0xaa79bf22598 @   90 : 63 fa 03 04 11    CallUndefinedReceiver2 r0, a0, a1, [17]
         0xaa79bf2259d @   95 : 0e                LdaUndefined
21543 S> 0xaa79bf2259e @   96 : a9                Return
Constant pool (size = 3)
0xaa79bf224e1: [FixedArray] in OldSpace
 - map: 0x3fc2dc0012d9 <Map(FIXED_ARRAY_TYPE)>
 - length: 3
           0: 0x0aa79bf0c579 <String[9]: #pendingcb>
           1: 0x04e986dc9ac9 <String[8]: #nextTick>
           2: 0x0aa79bf22491 <SharedFunctionInfo>
Handler Table (size = 0)
Source Position Table (size = 45)
0x0aa79bf225a1 <ByteArray[45]>
[generated bytecode for function: needFinish (0x358ffa86f849 <SharedFunctionInfo needFinish>)]
Bytecode length: 80
Parameter count 2
Register count 1
Frame size 8
Bytecode age: 0
19493 S> 0xaa79bf22716 @    0 : 2d 03 00 00       GetNamedProperty a0, [0], [0]
         0xaa79bf2271a @    4 : 97 4b             JumpIfToBooleanFalse [75] (0xaa79bf22765 @ 79)
19520 E> 0xaa79bf2271c @    6 : 2d 03 01 02       GetNamedProperty a0, [1], [2]
         0xaa79bf22720 @   10 : 54                ToBooleanLogicalNot
         0xaa79bf22721 @   11 : 99 44             JumpIfFalse [68] (0xaa79bf22765 @ 79)
19549 E> 0xaa79bf22723 @   13 : 2d 03 02 04       GetNamedProperty a0, [2], [4]
         0xaa79bf22727 @   17 : 97 3e             JumpIfToBooleanFalse [62] (0xaa79bf22765 @ 79)
19580 E> 0xaa79bf22729 @   19 : 2d 03 03 06       GetNamedProperty a0, [3], [6]
         0xaa79bf2272d @   23 : c4                Star0
         0xaa79bf2272e @   24 : 0c                LdaZero
19587 E> 0xaa79bf2272f @   25 : 6c fa 08          TestEqualStrict r0, [8]
         0xaa79bf22732 @   28 : 99 33             JumpIfFalse [51] (0xaa79bf22765 @ 79)
19613 E> 0xaa79bf22734 @   30 : 2d 03 04 09       GetNamedProperty a0, [4], [9]
         0xaa79bf22738 @   34 : 54                ToBooleanLogicalNot
         0xaa79bf22739 @   35 : 99 2c             JumpIfFalse [44] (0xaa79bf22765 @ 79)
19640 E> 0xaa79bf2273b @   37 : 2d 03 05 0b       GetNamedProperty a0, [5], [11]
         0xaa79bf2273f @   41 : c4                Star0
19649 E> 0xaa79bf22740 @   42 : 2d fa 03 0d       GetNamedProperty r0, [3], [13]
         0xaa79bf22744 @   46 : c4                Star0
         0xaa79bf22745 @   47 : 0c                LdaZero
19656 E> 0xaa79bf22746 @   48 : 6c fa 0f          TestEqualStrict r0, [15]
         0xaa79bf22749 @   51 : 99 1c             JumpIfFalse [28] (0xaa79bf22765 @ 79)
19682 E> 0xaa79bf2274b @   53 : 2d 03 06 10       GetNamedProperty a0, [6], [16]
         0xaa79bf2274f @   57 : 54                ToBooleanLogicalNot
         0xaa79bf22750 @   58 : 99 15             JumpIfFalse [21] (0xaa79bf22765 @ 79)
19711 E> 0xaa79bf22752 @   60 : 2d 03 07 12       GetNamedProperty a0, [7], [18]
         0xaa79bf22756 @   64 : 54                ToBooleanLogicalNot
         0xaa79bf22757 @   65 : 99 0e             JumpIfFalse [14] (0xaa79bf22765 @ 79)
19739 E> 0xaa79bf22759 @   67 : 2d 03 08 14       GetNamedProperty a0, [8], [20]
         0xaa79bf2275d @   71 : 54                ToBooleanLogicalNot
         0xaa79bf2275e @   72 : 99 07             JumpIfFalse [7] (0xaa79bf22765 @ 79)
19772 E> 0xaa79bf22760 @   74 : 2d 03 09 16       GetNamedProperty a0, [9], [22]
         0xaa79bf22764 @   78 : 54                ToBooleanLogicalNot
19786 S> 0xaa79bf22765 @   79 : a9                Return
Constant pool (size = 10)
0xaa79bf22681: [FixedArray] in OldSpace
 - map: 0x3fc2dc0012d9 <Map(FIXED_ARRAY_TYPE)>
 - length: 10
           0: 0x0aa79bf099b1 <String[6]: #ending>
           1: 0x04e986dd2131 <String[9]: #destroyed>
           2: 0x0aa79bf0a9e9 <String[11]: #constructed>
           3: 0x3fc2dc0078d1 <String[6]: #length>
           4: 0x04e986de43f9 <String[7]: #errored>
           5: 0x358ffa86ed09 <String[8]: #buffered>
           6: 0x358ffa858d09 <String[8]: #finished>
           7: 0x358ffa861da1 <String[7]: #writing>
           8: 0x188e9f02d561 <String[12]: #errorEmitted>
           9: 0x0aa79bf0aa71 <String[12]: #closeEmitted>
Handler Table (size = 0)
Source Position Table (size = 33)
0x0aa79bf22769 <ByteArray[33]>
[generated bytecode for function: destroyHooksExist (0x16e16e0aeba1 <SharedFunctionInfo destroyHooksExist>)]
Bytecode length: 13
Parameter count 1
Register count 2
Frame size 16
Bytecode age: 0
16369 S> 0xaa79bf2285e @    0 : 17 40             LdaImmutableCurrentContextSlot [64]
         0xaa79bf22860 @    2 : c4                Star0
         0xaa79bf22861 @    3 : 17 18             LdaImmutableCurrentContextSlot [24]
16385 E> 0xaa79bf22863 @    5 : aa 00             ThrowReferenceErrorIfHole [0]
         0xaa79bf22865 @    7 : c3                Star1
16376 E> 0xaa79bf22866 @    8 : 62 fa f9 00       CallUndefinedReceiver1 r0, r1, [0]
16395 S> 0xaa79bf2286a @   12 : a9                Return
Constant pool (size = 1)
0xaa79bf22811: [FixedArray] in OldSpace
 - map: 0x3fc2dc0012d9 <Map(FIXED_ARRAY_TYPE)>
 - length: 1
           0: 0x04e986dc3cf1 <String[8]: #kDestroy>
Handler Table (size = 0)
Source Position Table (size = 12)
0x0aa79bf22871 <ByteArray[12]>
[generated bytecode for function: emitAfterScript (0x16e16e0aece1 <SharedFunctionInfo emitAfterScript>)]
Bytecode length: 32
Parameter count 2
Register count 2
Frame size 16
Bytecode age: 0
17105 S> 0xaa79bf2294e @    0 : 17 40             LdaImmutableCurrentContextSlot [64]
         0xaa79bf22950 @    2 : c4                Star0
         0xaa79bf22951 @    3 : 17 17             LdaImmutableCurrentContextSlot [23]
17118 E> 0xaa79bf22953 @    5 : aa 00             ThrowReferenceErrorIfHole [0]
         0xaa79bf22955 @    7 : c3                Star1
17109 E> 0xaa79bf22956 @    8 : 62 fa f9 00       CallUndefinedReceiver1 r0, r1, [0]
         0xaa79bf2295a @   12 : 97 0b             JumpIfToBooleanFalse [11] (0xaa79bf22965 @ 23)
17131 S> 0xaa79bf2295c @   14 : 17 26             LdaImmutableCurrentContextSlot [38]
         0xaa79bf2295e @   16 : aa 01             ThrowReferenceErrorIfHole [1]
         0xaa79bf22960 @   18 : c4                Star0
17131 E> 0xaa79bf22961 @   19 : 62 fa 03 02       CallUndefinedReceiver1 r0, a0, [2]
17160 S> 0xaa79bf22965 @   23 : 17 48             LdaImmutableCurrentContextSlot [72]
         0xaa79bf22967 @   25 : c4                Star0
17160 E> 0xaa79bf22968 @   26 : 62 fa 03 04       CallUndefinedReceiver1 r0, a0, [4]
         0xaa79bf2296c @   30 : 0e                LdaUndefined
17186 S> 0xaa79bf2296d @   31 : a9                Return
Constant pool (size = 2)
0xaa79bf228f9: [FixedArray] in OldSpace
 - map: 0x3fc2dc0012d9 <Map(FIXED_ARRAY_TYPE)>
 - length: 2
           0: 0x04e986dc3cd9 <String[6]: #kAfter>
           1: 0x04e986dc3e61 <String[15]: #emitAfterNative>
Handler Table (size = 0)
Source Position Table (size = 20)
0x0aa79bf22971 <ByteArray[20]>
[generated bytecode for function: popAsyncContext (0x16e16e0aee21 <SharedFunctionInfo popAsyncContext>)]
Bytecode length: 167
Parameter count 2
Register count 5
Frame size 40
Bytecode age: 0
18225 S> 0xaa79bf22ab6 @    0 : 17 0b             LdaImmutableCurrentContextSlot [11]
         0xaa79bf22ab8 @    2 : aa 00             ThrowReferenceErrorIfHole [0]
         0xaa79bf22aba @    4 : c2                Star2
         0xaa79bf22abb @    5 : 17 1f             LdaImmutableCurrentContextSlot [31]
18243 E> 0xaa79bf22abd @    7 : aa 01             ThrowReferenceErrorIfHole [1]
18242 E> 0xaa79bf22abf @    9 : 2f f8 00          GetKeyedProperty r2, [0]
         0xaa79bf22ac2 @   12 : c4                Star0
18260 S> 0xaa79bf22ac3 @   13 : 0c                LdaZero
18276 E> 0xaa79bf22ac4 @   14 : 6c fa 02          TestEqualStrict r0, [2]
         0xaa79bf22ac7 @   17 : 99 04             JumpIfFalse [4] (0xaa79bf22acb @ 21)
18283 S> 0xaa79bf22ac9 @   19 : 12                LdaFalse
18296 S> 0xaa79bf22aca @   20 : a9                Return
18300 S> 0xaa79bf22acb @   21 : 17 41             LdaImmutableCurrentContextSlot [65]
         0xaa79bf22acd @   23 : c2                Star2
18304 E> 0xaa79bf22ace @   24 : 61 f8 03          CallUndefinedReceiver0 r2, [3]
         0xaa79bf22ad1 @   27 : 97 20             JumpIfToBooleanFalse [32] (0xaa79bf22af1 @ 59)
         0xaa79bf22ad3 @   29 : 17 0c             LdaImmutableCurrentContextSlot [12]
18327 E> 0xaa79bf22ad5 @   31 : aa 02             ThrowReferenceErrorIfHole [2]
         0xaa79bf22ad7 @   33 : c2                Star2
         0xaa79bf22ad8 @   34 : 17 1b             LdaImmutableCurrentContextSlot [27]
18343 E> 0xaa79bf22ada @   36 : aa 03             ThrowReferenceErrorIfHole [3]
18342 E> 0xaa79bf22adc @   38 : 2f f8 05          GetKeyedProperty r2, [5]
         0xaa79bf22adf @   41 : c2                Star2
         0xaa79bf22ae0 @   42 : 0b 03             Ldar a0
18362 E> 0xaa79bf22ae2 @   44 : 6c f8 07          TestEqualStrict r2, [7]
         0xaa79bf22ae5 @   47 : 98 0c             JumpIfTrue [12] (0xaa79bf22af1 @ 59)
18444 S> 0xaa79bf22ae7 @   49 : 17 0f             LdaImmutableCurrentContextSlot [15]
         0xaa79bf22ae9 @   51 : aa 04             ThrowReferenceErrorIfHole [4]
         0xaa79bf22aeb @   53 : c2                Star2
18451 E> 0xaa79bf22aec @   54 : 62 f8 03 08       CallUndefinedReceiver1 r2, a0, [8]
18477 S> 0xaa79bf22af0 @   58 : a9                Return
18500 S> 0xaa79bf22af1 @   59 : 0b fa             Ldar r0
18512 E> 0xaa79bf22af3 @   61 : 45 01 0a          SubSmi [1], [10]
         0xaa79bf22af6 @   64 : c3                Star1
18519 S> 0xaa79bf22af7 @   65 : 17 0c             LdaImmutableCurrentContextSlot [12]
         0xaa79bf22af9 @   67 : aa 02             ThrowReferenceErrorIfHole [2]
         0xaa79bf22afb @   69 : c2                Star2
         0xaa79bf22afc @   70 : 17 1b             LdaImmutableCurrentContextSlot [27]
18535 E> 0xaa79bf22afe @   72 : aa 03             ThrowReferenceErrorIfHole [3]
         0xaa79bf22b00 @   74 : c1                Star3
         0xaa79bf22b01 @   75 : 17 09             LdaImmutableCurrentContextSlot [9]
18556 E> 0xaa79bf22b03 @   77 : aa 05             ThrowReferenceErrorIfHole [5]
         0xaa79bf22b05 @   79 : c0                Star4
18567 E> 0xaa79bf22b06 @   80 : 2d f6 06 0b       GetNamedProperty r4, [6], [11]
         0xaa79bf22b0a @   84 : c0                Star4
         0xaa79bf22b0b @   85 : 0b f9             Ldar r1
18585 E> 0xaa79bf22b0d @   87 : 46 02 0d          MulSmi [2], [13]
18582 E> 0xaa79bf22b10 @   90 : 2f f6 0e          GetKeyedProperty r4, [14]
18554 E> 0xaa79bf22b13 @   93 : 34 f8 f7 10       SetKeyedProperty r2, r3, [16]
18598 S> 0xaa79bf22b17 @   97 : 17 0c             LdaImmutableCurrentContextSlot [12]
         0xaa79bf22b19 @   99 : aa 02             ThrowReferenceErrorIfHole [2]
         0xaa79bf22b1b @  101 : c2                Star2
         0xaa79bf22b1c @  102 : 17 1d             LdaImmutableCurrentContextSlot [29]
18614 E> 0xaa79bf22b1e @  104 : aa 07             ThrowReferenceErrorIfHole [7]
         0xaa79bf22b20 @  106 : c1                Star3
         0xaa79bf22b21 @  107 : 17 09             LdaImmutableCurrentContextSlot [9]
18633 E> 0xaa79bf22b23 @  109 : aa 05             ThrowReferenceErrorIfHole [5]
         0xaa79bf22b25 @  111 : c0                Star4
18644 E> 0xaa79bf22b26 @  112 : 2d f6 06 0b       GetNamedProperty r4, [6], [11]
         0xaa79bf22b2a @  116 : c0                Star4
         0xaa79bf22b2b @  117 : 0b f9             Ldar r1
18662 E> 0xaa79bf22b2d @  119 : 46 02 13          MulSmi [2], [19]
18671 E> 0xaa79bf22b30 @  122 : 44 01 12          AddSmi [1], [18]
18659 E> 0xaa79bf22b33 @  125 : 2f f6 14          GetKeyedProperty r4, [20]
18631 E> 0xaa79bf22b36 @  128 : 34 f8 f7 16       SetKeyedProperty r2, r3, [22]
18679 S> 0xaa79bf22b3a @  132 : 17 0d             LdaImmutableCurrentContextSlot [13]
         0xaa79bf22b3c @  134 : aa 08             ThrowReferenceErrorIfHole [8]
         0xaa79bf22b3e @  136 : c1                Star3
18705 E> 0xaa79bf22b3f @  137 : 2d f7 09 18       GetNamedProperty r3, [9], [24]
         0xaa79bf22b43 @  141 : c2                Star2
18705 E> 0xaa79bf22b44 @  142 : 5d f8 f7 1a       CallProperty0 r2, r3, [26]
18714 S> 0xaa79bf22b48 @  146 : 17 0b             LdaImmutableCurrentContextSlot [11]
         0xaa79bf22b4a @  148 : aa 00             ThrowReferenceErrorIfHole [0]
         0xaa79bf22b4c @  150 : c2                Star2
         0xaa79bf22b4d @  151 : 17 1f             LdaImmutableCurrentContextSlot [31]
18732 E> 0xaa79bf22b4f @  153 : aa 01             ThrowReferenceErrorIfHole [1]
         0xaa79bf22b51 @  155 : c1                Star3
         0xaa79bf22b52 @  156 : 0b f9             Ldar r1
18746 E> 0xaa79bf22b54 @  158 : 34 f8 f7 1c       SetKeyedProperty r2, r3, [28]
18758 S> 0xaa79bf22b58 @  162 : 0c                LdaZero
18772 E> 0xaa79bf22b59 @  163 : 6e f9 1e          TestGreaterThan r1, [30]
18776 S> 0xaa79bf22b5c @  166 : a9                Return
Constant pool (size = 10)
0xaa79bf22a21: [FixedArray] in OldSpace
 - map: 0x3fc2dc0012d9 <Map(FIXED_ARRAY_TYPE)>
 - length: 10
           0: 0x04e986dc3b39 <String[17]: #async_hook_fields>
           1: 0x04e986dc3dd1 <String[12]: #kStackLength>
           2: 0x04e986dc3b61 <String[15]: #async_id_fields>
           3: 0x04e986dc3d41 <String[17]: #kExecutionAsyncId>
           4: 0x04e986dc3bd9 <String[16]: #popAsyncContext_>
           5: 0x04e986dc3af1 <String[10]: #async_wrap>
           6: 0x04e986dd1de1 <String[15]: #async_ids_stack>
           7: 0x04e986dc3d89 <String[15]: #kTriggerAsyncId>
           8: 0x04e986dc3b81 <String[25]: #execution_async_resources>
           9: 0x04e986dd6131 <String[3]: #pop>
Handler Table (size = 0)
Source Position Table (size = 92)
0x0aa79bf22b61 <ByteArray[92]>
[generated bytecode for function: enabledHooksExist (0x16e16e0aeab1 <SharedFunctionInfo enabledHooksExist>)]
Bytecode length: 13
Parameter count 1
Register count 2
Frame size 16
Bytecode age: 0
16192 S> 0xaa79bf22c96 @    0 : 17 40             LdaImmutableCurrentContextSlot [64]
         0xaa79bf22c98 @    2 : c4                Star0
         0xaa79bf22c99 @    3 : 17 1a             LdaImmutableCurrentContextSlot [26]
16208 E> 0xaa79bf22c9b @    5 : aa 00             ThrowReferenceErrorIfHole [0]
         0xaa79bf22c9d @    7 : c3                Star1
16199 E> 0xaa79bf22c9e @    8 : 62 fa f9 00       CallUndefinedReceiver1 r0, r1, [0]
16216 S> 0xaa79bf22ca2 @   12 : a9                Return
Constant pool (size = 1)
0xaa79bf22c49: [FixedArray] in OldSpace
 - map: 0x3fc2dc0012d9 <Map(FIXED_ARRAY_TYPE)>
 - length: 1
           0: 0x04e986dc3d29 <String[6]: #kCheck>
Handler Table (size = 0)
Source Position Table (size = 12)
0x0aa79bf22ca9 <ByteArray[12]>
[generated bytecode for function: processPromiseRejections (0x143d9dd0a261 <SharedFunctionInfo processPromiseRejections>)]
Bytecode length: 632
Parameter count 1
Register count 24
Frame size 192
Bytecode age: 0
 6743 S> 0xaa79bf22f66 @    0 : 17 1a             LdaImmutableCurrentContextSlot [26]
         0xaa79bf22f68 @    2 : aa 00             ThrowReferenceErrorIfHole [0]
         0xaa79bf22f6a @    4 : 18 e9             Star r17
 6766 E> 0xaa79bf22f6c @    6 : 2d e9 01 00       GetNamedProperty r17, [1], [0]
         0xaa79bf22f70 @   10 : 18 e9             Star r17
         0xaa79bf22f72 @   12 : 0c                LdaZero
 6773 E> 0xaa79bf22f73 @   13 : 6e e9 02          TestGreaterThan r17, [2]
         0xaa79bf22f76 @   16 : c4                Star0
 6818 S> 0xaa79bf22f77 @   17 : 17 1a             LdaImmutableCurrentContextSlot [26]
         0xaa79bf22f79 @   19 : aa 00             ThrowReferenceErrorIfHole [0]
         0xaa79bf22f7b @   21 : 18 e9             Star r17
 6811 E> 0xaa79bf22f7d @   23 : 2d e9 01 00       GetNamedProperty r17, [1], [0]
         0xaa79bf22f81 @   27 : 18 e9             Star r17
         0xaa79bf22f83 @   29 : 0c                LdaZero
 6818 E> 0xaa79bf22f84 @   30 : 6e e9 03          TestGreaterThan r17, [3]
         0xaa79bf22f87 @   33 : 99 48             JumpIfFalse [72] (0xaa79bf22fcf @ 105)
 6858 S> 0xaa79bf22f89 @   35 : 17 05             LdaImmutableCurrentContextSlot [5]
         0xaa79bf22f8b @   37 : aa 02             ThrowReferenceErrorIfHole [2]
         0xaa79bf22f8d @   39 : 18 e9             Star r17
         0xaa79bf22f8f @   41 : 17 1a             LdaImmutableCurrentContextSlot [26]
 6878 E> 0xaa79bf22f91 @   43 : aa 00             ThrowReferenceErrorIfHole [0]
         0xaa79bf22f93 @   45 : 18 e8             Star r18
 6858 E> 0xaa79bf22f95 @   47 : 62 e9 e8 04       CallUndefinedReceiver1 r17, r18, [4]
         0xaa79bf22f99 @   51 : 18 e9             Star r17
 6837 E> 0xaa79bf22f9b @   53 : 2d e9 03 06       GetNamedProperty r17, [3], [6]
         0xaa79bf22f9f @   57 : b5                Star15
 6846 E> 0xaa79bf22fa0 @   58 : 2d e9 04 08       GetNamedProperty r17, [4], [8]
         0xaa79bf22fa4 @   62 : 18 ea             Star r16
 6907 S> 0xaa79bf22fa6 @   64 : 17 02             LdaImmutableCurrentContextSlot [2]
         0xaa79bf22fa8 @   66 : 18 e8             Star r18
 6920 E> 0xaa79bf22faa @   68 : 2d e8 05 0a       GetNamedProperty r18, [5], [10]
         0xaa79bf22fae @   72 : 18 e9             Star r17
         0xaa79bf22fb0 @   74 : 13 06             LdaConstant [6]
         0xaa79bf22fb2 @   76 : 18 e7             Star r19
 6920 E> 0xaa79bf22fb4 @   78 : 5f e9 e8 e7 eb 0c CallProperty2 r17, r18, r19, r15, [12]
         0xaa79bf22fba @   84 : 96 11             JumpIfToBooleanTrue [17] (0xaa79bf22fcb @ 101)
 6963 S> 0xaa79bf22fbc @   86 : 17 02             LdaImmutableCurrentContextSlot [2]
         0xaa79bf22fbe @   88 : 18 e8             Star r18
 6971 E> 0xaa79bf22fc0 @   90 : 2d e8 07 0e       GetNamedProperty r18, [7], [14]
         0xaa79bf22fc4 @   94 : 18 e9             Star r17
 6971 E> 0xaa79bf22fc6 @   96 : 5e e9 e8 ea 10    CallProperty1 r17, r18, r16, [16]
 6781 E> 0xaa79bf22fcb @  101 : 89 54 00 12       JumpLoop [84], [0], [18] (0xaa79bf22f77 @ 17)
 7016 S> 0xaa79bf22fcf @  105 : 17 19             LdaImmutableCurrentContextSlot [25]
         0xaa79bf22fd1 @  107 : aa 08             ThrowReferenceErrorIfHole [8]
         0xaa79bf22fd3 @  109 : 18 e9             Star r17
 7043 E> 0xaa79bf22fd5 @  111 : 2d e9 01 13       GetNamedProperty r17, [1], [19]
         0xaa79bf22fd9 @  115 : c3                Star1
 7063 S> 0xaa79bf22fda @  116 : 0b f9             Ldar r1
         0xaa79bf22fdc @  118 : 75 15             ToNumeric [21]
         0xaa79bf22fde @  120 : 18 e9             Star r17
         0xaa79bf22fe0 @  122 : 51 15             Dec [21]
         0xaa79bf22fe2 @  124 : c3                Star1
         0xaa79bf22fe3 @  125 : 0b e9             Ldar r17
 7063 E> 0xaa79bf22fe5 @  127 : 95 1c             JumpIfToBooleanFalseConstant [28] (0xaa79bf231c8 @ 610)
 7089 S> 0xaa79bf22fe7 @  129 : 17 05             LdaImmutableCurrentContextSlot [5]
         0xaa79bf22fe9 @  131 : aa 02             ThrowReferenceErrorIfHole [2]
         0xaa79bf22feb @  133 : 18 e9             Star r17
         0xaa79bf22fed @  135 : 17 19             LdaImmutableCurrentContextSlot [25]
 7109 E> 0xaa79bf22fef @  137 : aa 08             ThrowReferenceErrorIfHole [8]
         0xaa79bf22ff1 @  139 : 18 e8             Star r18
 7089 E> 0xaa79bf22ff3 @  141 : 62 e9 e8 16       CallUndefinedReceiver1 r17, r18, [22]
         0xaa79bf22ff7 @  145 : c2                Star2
 7162 S> 0xaa79bf22ff8 @  146 : 17 18             LdaImmutableCurrentContextSlot [24]
         0xaa79bf22ffa @  148 : aa 09             ThrowReferenceErrorIfHole [9]
         0xaa79bf22ffc @  150 : 18 e8             Star r18
 7185 E> 0xaa79bf22ffe @  152 : 2d e8 0a 18       GetNamedProperty r18, [10], [24]
         0xaa79bf23002 @  156 : 18 e9             Star r17
 7185 E> 0xaa79bf23004 @  158 : 5e e9 e8 f8 1a    CallProperty1 r17, r18, r2, [26]
         0xaa79bf23009 @  163 : c1                Star3
 7203 S> 0xaa79bf2300a @  164 : 9d 04             JumpIfNotUndefined [4] (0xaa79bf2300e @ 168)
 7242 S> 0xaa79bf2300c @  166 : 8b 1b             JumpConstant [27] (0xaa79bf231c0 @ 602)
 7262 S> 0xaa79bf2300e @  168 : 11                LdaTrue
 7281 E> 0xaa79bf2300f @  169 : 32 f7 0b 1c       SetNamedProperty r3, [11], [28]
 7301 S> 0xaa79bf23013 @  173 : 2d f7 0c 1e       GetNamedProperty r3, [12], [30]
         0xaa79bf23017 @  177 : c0                Star4
 7309 E> 0xaa79bf23018 @  178 : 2d f7 0d 20       GetNamedProperty r3, [13], [32]
         0xaa79bf2301c @  182 : bf                Star5
 7314 E> 0xaa79bf2301d @  183 : 2d f7 05 22       GetNamedProperty r3, [5], [34]
         0xaa79bf23021 @  187 : be                Star6
 7355 S> 0xaa79bf23022 @  188 : 11                LdaTrue
         0xaa79bf23023 @  189 : bd                Star7
 7475 S> 0xaa79bf23024 @  190 : 0b f8             Ldar r2
         0xaa79bf23026 @  192 : 19 f8 e9          Mov r2, r17
         0xaa79bf23029 @  195 : 9e 04             JumpIfUndefinedOrNull [4] (0xaa79bf2302d @ 199)
         0xaa79bf2302b @  197 : 8a 07             Jump [7] (0xaa79bf23032 @ 204)
 7371 E> 0xaa79bf2302d @  199 : 65 c6 00 e9 01    CallRuntime [ThrowPatternAssignmentNonCoercible], r17-r17
         0xaa79bf23032 @  204 : 17 14             LdaImmutableCurrentContextSlot [20]
 7380 E> 0xaa79bf23034 @  206 : aa 0e             ThrowReferenceErrorIfHole [14]
         0xaa79bf23036 @  208 : 73 e8             ToName r18
         0xaa79bf23038 @  210 : 0b e8             Ldar r18
         0xaa79bf2303a @  212 : 2f e9 24          GetKeyedProperty r17, [36]
         0xaa79bf2303d @  215 : bc                Star8
         0xaa79bf2303e @  216 : 17 15             LdaImmutableCurrentContextSlot [21]
 7420 E> 0xaa79bf23040 @  218 : aa 0f             ThrowReferenceErrorIfHole [15]
         0xaa79bf23042 @  220 : 73 e8             ToName r18
         0xaa79bf23044 @  222 : 0b e8             Ldar r18
         0xaa79bf23046 @  224 : 2f e9 26          GetKeyedProperty r17, [38]
         0xaa79bf23049 @  227 : bb                Star9
 7650 S> 0xaa79bf2304a @  228 : 0b f2             Ldar r8
         0xaa79bf2304c @  230 : 20 05             TestTypeOf #5
         0xaa79bf2304e @  232 : 98 16             JumpIfTrue [22] (0xaa79bf23064 @ 254)
 7701 S> 0xaa79bf23050 @  234 : 17 12             LdaImmutableCurrentContextSlot [18]
         0xaa79bf23052 @  236 : aa 10             ThrowReferenceErrorIfHole [16]
         0xaa79bf23054 @  238 : 18 e9             Star r17
         0xaa79bf23056 @  240 : 19 f2 e8          Mov r8, r18
         0xaa79bf23059 @  243 : 19 f1 e7          Mov r9, r19
         0xaa79bf2305c @  246 : 19 f8 e6          Mov r2, r20
 7701 E> 0xaa79bf2305f @  249 : 60 e9 e8 03 28    CallUndefinedReceiver r17, r18-r20, [40]
         0xaa79bf23064 @  254 : 19 ff e7          Mov <context>, r19
 7821 S> 0xaa79bf23067 @  257 : 16 21             LdaCurrentContextSlot [33]
         0xaa79bf23069 @  259 : aa 11             ThrowReferenceErrorIfHole [17]
         0xaa79bf2306b @  261 : 18 e6             Star r20
         0xaa79bf2306d @  263 : 17 1e             LdaImmutableCurrentContextSlot [30]
 7869 E> 0xaa79bf2306f @  265 : aa 12             ThrowReferenceErrorIfHole [18]
         0xaa79bf23071 @  267 : 6c e6 2a          TestEqualStrict r20, [42]
         0xaa79bf23074 @  270 : 98 28             JumpIfTrue [40] (0xaa79bf2309c @ 310)
         0xaa79bf23076 @  272 : 17 1c             LdaImmutableCurrentContextSlot [28]
 8524 E> 0xaa79bf23078 @  274 : aa 13             ThrowReferenceErrorIfHole [19]
         0xaa79bf2307a @  276 : 6c e6 2a          TestEqualStrict r20, [42]
         0xaa79bf2307d @  279 : 98 86             JumpIfTrue [134] (0xaa79bf23103 @ 413)
         0xaa79bf2307f @  281 : 17 1d             LdaImmutableCurrentContextSlot [29]
 8640 E> 0xaa79bf23081 @  283 : aa 14             ThrowReferenceErrorIfHole [20]
         0xaa79bf23083 @  285 : 6c e6 2a          TestEqualStrict r20, [42]
         0xaa79bf23086 @  288 : 98 8d             JumpIfTrue [141] (0xaa79bf23113 @ 429)
         0xaa79bf23088 @  290 : 17 1f             LdaImmutableCurrentContextSlot [31]
 8814 E> 0xaa79bf2308a @  292 : aa 15             ThrowReferenceErrorIfHole [21]
         0xaa79bf2308c @  294 : 6c e6 2a          TestEqualStrict r20, [42]
         0xaa79bf2308f @  297 : 98 9d             JumpIfTrue [157] (0xaa79bf2312c @ 454)
         0xaa79bf23091 @  299 : 17 20             LdaImmutableCurrentContextSlot [32]
 9258 E> 0xaa79bf23093 @  301 : aa 16             ThrowReferenceErrorIfHole [22]
         0xaa79bf23095 @  303 : 6c e6 2a          TestEqualStrict r20, [42]
         0xaa79bf23098 @  306 : 98 ce             JumpIfTrue [206] (0xaa79bf23166 @ 512)
         0xaa79bf2309a @  308 : 8a f4             Jump [244] (0xaa79bf2318e @ 552)
 7921 S> 0xaa79bf2309c @  310 : 17 23             LdaImmutableCurrentContextSlot [35]
         0xaa79bf2309e @  312 : 18 e6             Star r20
 7921 E> 0xaa79bf230a0 @  314 : 62 e6 f6 2b       CallUndefinedReceiver1 r20, r4, [43]
         0xaa79bf230a4 @  318 : 97 06             JumpIfToBooleanFalse [6] (0xaa79bf230aa @ 324)
         0xaa79bf230a6 @  320 : 0b f6             Ldar r4
         0xaa79bf230a8 @  322 : 8a 0a             Jump [10] (0xaa79bf230b2 @ 332)
         0xaa79bf230aa @  324 : 17 2d             LdaImmutableCurrentContextSlot [45]
         0xaa79bf230ac @  326 : 18 e6             Star r20
 7964 E> 0xaa79bf230ae @  328 : 62 e6 f6 2d       CallUndefinedReceiver1 r20, r4, [45]
         0xaa79bf230b2 @  332 : b7                Star13
 8080 S> 0xaa79bf230b3 @  333 : 17 10             LdaImmutableCurrentContextSlot [16]
         0xaa79bf230b5 @  335 : aa 17             ThrowReferenceErrorIfHole [23]
         0xaa79bf230b7 @  337 : 18 e6             Star r20
         0xaa79bf230b9 @  339 : 11                LdaTrue
         0xaa79bf230ba @  340 : 18 e4             Star r22
 8080 E> 0xaa79bf230bc @  342 : 63 e6 ed e4 2f    CallUndefinedReceiver2 r20, r13, r22, [47]
 8145 S> 0xaa79bf230c1 @  347 : 0b f2             Ldar r8
         0xaa79bf230c3 @  349 : 20 05             TestTypeOf #5
         0xaa79bf230c5 @  351 : 98 22             JumpIfTrue [34] (0xaa79bf230e7 @ 385)
 8202 S> 0xaa79bf230c7 @  353 : 17 12             LdaImmutableCurrentContextSlot [18]
         0xaa79bf230c9 @  355 : aa 10             ThrowReferenceErrorIfHole [16]
         0xaa79bf230cb @  357 : 18 e6             Star r20
         0xaa79bf230cd @  359 : 17 14             LdaImmutableCurrentContextSlot [20]
 8242 E> 0xaa79bf230cf @  361 : aa 0e             ThrowReferenceErrorIfHole [14]
 8241 E> 0xaa79bf230d1 @  363 : 2f f8 31          GetKeyedProperty r2, [49]
         0xaa79bf230d4 @  366 : 18 e5             Star r21
         0xaa79bf230d6 @  368 : 17 15             LdaImmutableCurrentContextSlot [21]
 8281 E> 0xaa79bf230d8 @  370 : aa 0f             ThrowReferenceErrorIfHole [15]
 8280 E> 0xaa79bf230da @  372 : 2f f8 33          GetKeyedProperty r2, [51]
         0xaa79bf230dd @  375 : 18 e4             Star r22
         0xaa79bf230df @  377 : 19 f8 e3          Mov r2, r23
 8202 E> 0xaa79bf230e2 @  380 : 60 e6 e5 03 35    CallUndefinedReceiver r20, r21-r23, [53]
 8380 S> 0xaa79bf230e7 @  385 : 19 f6 e5          Mov r4, r21
         0xaa79bf230ea @  388 : 19 f8 e4          Mov r2, r22
         0xaa79bf230ed @  391 : 19 f7 e3          Mov r3, r23
 8380 E> 0xaa79bf230f0 @  394 : 60 f4 e5 03 37    CallUndefinedReceiver r6, r21-r23, [55]
         0xaa79bf230f5 @  399 : b6                Star14
 8426 S> 0xaa79bf230f6 @  400 : 96 0b             JumpIfToBooleanTrue [11] (0xaa79bf23101 @ 411)
 8440 S> 0xaa79bf230f8 @  402 : 17 2b             LdaImmutableCurrentContextSlot [43]
         0xaa79bf230fa @  404 : 18 e6             Star r20
 8440 E> 0xaa79bf230fc @  406 : 63 e6 f5 f6 39    CallUndefinedReceiver2 r20, r5, r4, [57]
 8494 S> 0xaa79bf23101 @  411 : 8a 8d             Jump [141] (0xaa79bf2318e @ 552)
 8564 S> 0xaa79bf23103 @  413 : 19 f6 e5          Mov r4, r21
         0xaa79bf23106 @  416 : 19 f8 e4          Mov r2, r22
         0xaa79bf23109 @  419 : 19 f7 e3          Mov r3, r23
 8564 E> 0xaa79bf2310c @  422 : 60 f4 e5 03 3b    CallUndefinedReceiver r6, r21-r23, [59]
 8610 S> 0xaa79bf23111 @  427 : 8a 7d             Jump [125] (0xaa79bf2318e @ 552)
 8684 S> 0xaa79bf23113 @  429 : 19 f6 e5          Mov r4, r21
         0xaa79bf23116 @  432 : 19 f8 e4          Mov r2, r22
         0xaa79bf23119 @  435 : 19 f7 e3          Mov r3, r23
 8684 E> 0xaa79bf2311c @  438 : 60 f4 e5 03 3d    CallUndefinedReceiver r6, r21-r23, [61]
 8730 S> 0xaa79bf23121 @  443 : 17 2b             LdaImmutableCurrentContextSlot [43]
         0xaa79bf23123 @  445 : 18 e6             Star r20
 8730 E> 0xaa79bf23125 @  447 : 63 e6 f5 f6 3f    CallUndefinedReceiver2 r20, r5, r4, [63]
 8784 S> 0xaa79bf2312a @  452 : 8a 64             Jump [100] (0xaa79bf2318e @ 552)
 8869 S> 0xaa79bf2312c @  454 : 19 f6 e5          Mov r4, r21
         0xaa79bf2312f @  457 : 19 f8 e4          Mov r2, r22
         0xaa79bf23132 @  460 : 19 f7 e3          Mov r3, r23
 8869 E> 0xaa79bf23135 @  463 : 60 f4 e5 03 41    CallUndefinedReceiver r6, r21-r23, [65]
         0xaa79bf2313a @  468 : b9                Star11
 8915 S> 0xaa79bf2313b @  469 : 96 29             JumpIfToBooleanTrue [41] (0xaa79bf23164 @ 510)
 8955 S> 0xaa79bf2313d @  471 : 17 23             LdaImmutableCurrentContextSlot [35]
         0xaa79bf2313f @  473 : 18 e6             Star r20
 8955 E> 0xaa79bf23141 @  475 : 62 e6 f6 43       CallUndefinedReceiver1 r20, r4, [67]
         0xaa79bf23145 @  479 : 97 06             JumpIfToBooleanFalse [6] (0xaa79bf2314b @ 485)
         0xaa79bf23147 @  481 : 0b f6             Ldar r4
         0xaa79bf23149 @  483 : 8a 0a             Jump [10] (0xaa79bf23153 @ 493)
         0xaa79bf2314b @  485 : 17 2d             LdaImmutableCurrentContextSlot [45]
         0xaa79bf2314d @  487 : 18 e6             Star r20
 9000 E> 0xaa79bf2314f @  489 : 62 e6 f6 45       CallUndefinedReceiver1 r20, r4, [69]
         0xaa79bf23153 @  493 : b8                Star12
 9122 S> 0xaa79bf23154 @  494 : 17 10             LdaImmutableCurrentContextSlot [16]
         0xaa79bf23156 @  496 : aa 17             ThrowReferenceErrorIfHole [23]
         0xaa79bf23158 @  498 : 18 e6             Star r20
         0xaa79bf2315a @  500 : 11                LdaTrue
         0xaa79bf2315b @  501 : 18 e4             Star r22
 9122 E> 0xaa79bf2315d @  503 : 63 e6 ee e4 47    CallUndefinedReceiver2 r20, r12, r22, [71]
 9189 S> 0xaa79bf23162 @  508 : 12                LdaFalse
         0xaa79bf23163 @  509 : bd                Star7
 9228 S> 0xaa79bf23164 @  510 : 8a 2a             Jump [42] (0xaa79bf2318e @ 552)
 9325 S> 0xaa79bf23166 @  512 : 19 f6 e5          Mov r4, r21
         0xaa79bf23169 @  515 : 19 f8 e4          Mov r2, r22
         0xaa79bf2316c @  518 : 19 f7 e3          Mov r3, r23
 9325 E> 0xaa79bf2316f @  521 : 60 f4 e5 03 49    CallUndefinedReceiver r6, r21-r23, [73]
         0xaa79bf23174 @  526 : ba                Star10
 9371 S> 0xaa79bf23175 @  527 : 96 17             JumpIfToBooleanTrue [23] (0xaa79bf2318c @ 550)
 9399 S> 0xaa79bf23177 @  529 : 17 2b             LdaImmutableCurrentContextSlot [43]
         0xaa79bf23179 @  531 : 18 e6             Star r20
 9399 E> 0xaa79bf2317b @  533 : 63 e6 f5 f6 4b    CallUndefinedReceiver2 r20, r5, r4, [75]
 9455 S> 0xaa79bf23180 @  538 : 17 02             LdaImmutableCurrentContextSlot [2]
         0xaa79bf23182 @  540 : 18 e6             Star r20
         0xaa79bf23184 @  542 : 17 11             LdaImmutableCurrentContextSlot [17]
 9474 E> 0xaa79bf23186 @  544 : aa 18             ThrowReferenceErrorIfHole [24]
 9472 E> 0xaa79bf23188 @  546 : 32 e6 19 4d       SetNamedProperty r20, [25], [77]
 9515 S> 0xaa79bf2318c @  550 : 8a 02             Jump [2] (0xaa79bf2318e @ 552)
         0xaa79bf2318e @  552 : 0d ff             LdaSmi [-1]
         0xaa79bf23190 @  554 : 18 e8             Star r18
         0xaa79bf23192 @  556 : 18 e9             Star r17
         0xaa79bf23194 @  558 : 8a 07             Jump [7] (0xaa79bf2319b @ 565)
         0xaa79bf23196 @  560 : 18 e8             Star r18
         0xaa79bf23198 @  562 : 0c                LdaZero
         0xaa79bf23199 @  563 : 18 e9             Star r17
         0xaa79bf2319b @  565 : 10                LdaTheHole
         0xaa79bf2319c @  566 : a6                SetPendingMessage
 9562 S> 0xaa79bf2319d @  567 : 18 e7             Star r19
         0xaa79bf2319f @  569 : 0b f3             Ldar r7
         0xaa79bf231a1 @  571 : 97 12             JumpIfToBooleanFalse [18] (0xaa79bf231b3 @ 589)
 9585 S> 0xaa79bf231a3 @  573 : 0b f2             Ldar r8
         0xaa79bf231a5 @  575 : 20 05             TestTypeOf #5
         0xaa79bf231a7 @  577 : 98 0c             JumpIfTrue [12] (0xaa79bf231b3 @ 589)
 9640 S> 0xaa79bf231a9 @  579 : 17 13             LdaImmutableCurrentContextSlot [19]
         0xaa79bf231ab @  581 : aa 1a             ThrowReferenceErrorIfHole [26]
         0xaa79bf231ad @  583 : 18 e6             Star r20
 9640 E> 0xaa79bf231af @  585 : 62 e6 f2 4f       CallUndefinedReceiver1 r20, r8, [79]
         0xaa79bf231b3 @  589 : 0b e7             Ldar r19
         0xaa79bf231b5 @  591 : a6                SetPendingMessage
         0xaa79bf231b6 @  592 : 0c                LdaZero
         0xaa79bf231b7 @  593 : 1c e9             TestReferenceEqual r17
         0xaa79bf231b9 @  595 : 99 05             JumpIfFalse [5] (0xaa79bf231be @ 600)
         0xaa79bf231bb @  597 : 0b e8             Ldar r18
         0xaa79bf231bd @  599 : a8                ReThrow
 9701 S> 0xaa79bf231be @  600 : 11                LdaTrue
         0xaa79bf231bf @  601 : c4                Star0
 7053 E> 0xaa79bf231c0 @  602 : 00 89 e7 01 00 00 51 00 JumpLoop.Wide [487], [0], [81] (0xaa79bf22fda @ 116)
 9747 S> 0xaa79bf231c8 @  610 : 0b fa             Ldar r0
         0xaa79bf231ca @  612 : 96 13             JumpIfToBooleanTrue [19] (0xaa79bf231dd @ 631)
         0xaa79bf231cc @  614 : 17 19             LdaImmutableCurrentContextSlot [25]
 9798 E> 0xaa79bf231ce @  616 : aa 08             ThrowReferenceErrorIfHole [8]
         0xaa79bf231d0 @  618 : 18 e9             Star r17
 9825 E> 0xaa79bf231d2 @  620 : 2d e9 01 13       GetNamedProperty r17, [1], [19]
         0xaa79bf231d6 @  624 : 18 e9             Star r17
         0xaa79bf231d8 @  626 : 0c                LdaZero
 9832 E> 0xaa79bf231d9 @  627 : 6c e9 52          TestEqualStrict r17, [82]
         0xaa79bf231dc @  630 : 55                LogicalNot
 9838 S> 0xaa79bf231dd @  631 : a9                Return
Constant pool (size = 29)
0xaa79bf22e39: [FixedArray] in OldSpace
 - map: 0x3fc2dc0012d9 <Map(FIXED_ARRAY_TYPE)>
 - length: 29
           0: 0x04e986dc9d71 <String[22]: #asyncHandledRejections>
           1: 0x3fc2dc0078d1 <String[6]: #length>
           2: 0x04e986dc6f49 <String[19]: #ArrayPrototypeShift>
           3: 0x04e986dd2e89 <String[7]: #promise>
           4: 0x188e9f02e5d1 <String[7]: #warning>
           5: 0x04e986dc74d1 <String[4]: #emit>
           6: 0x0aa79bf22d11 <String[16]: #rejectionHandled>
           7: 0x04e986dc7691 <String[11]: #emitWarning>
           8: 0x04e986dc9d41 <String[26]: #pendingUnhandledRejections>
           9: 0x04e986dc9d19 <String[22]: #maybeUnhandledPromises>
          10: 0x3fc2dc0073f1 <String[3]: #get>
          11: 0x04e986dc4df9 <String[6]: #warned>
          12: 0x3fc2dc00bc01 <String[6]: #reason>
          13: 0x04e986dd3371 <String[3]: #uid>
          14: 0x04e986dc9ca9 <String[14]: #kAsyncIdSymbol>
          15: 0x04e986dc9cc9 <String[21]: #kTriggerAsyncIdSymbol>
          16: 0x04e986dc4261 <String[16]: #pushAsyncContext>
          17: 0x04e986dc9eb1 <String[23]: #unhandledRejectionsMode>
          18: 0x04e986dc9e19 <String[26]: #kStrictUnhandledRejections>
          19: 0x04e986dc9db9 <String[26]: #kIgnoreUnhandledRejections>
          20: 0x04e986dc9de9 <String[30]: #kAlwaysWarnUnhandledRejections>
          21: 0x04e986dc9e49 <String[25]: #kThrowUnhandledRejections>
          22: 0x04e986dc9e79 <String[37]: #kWarnWithErrorCodeUnhandledRejections>
          23: 0x04e986dc9c81 <String[24]: #triggerUncaughtException>
          24: 0x04e986dc3ac9 <String[17]: #kGenericUserError>
          25: 0x04e986dc2779 <String[8]: #exitCode>
          26: 0x04e986dc4281 <String[15]: #popAsyncContext>
          27: 436
          28: 483
Handler Table (size = 16)
   from   to       hdlr (prediction,   data)
  ( 257, 552)  ->   560 (prediction=0, data=19)
Source Position Table (size = 268)
0x0aa79bf231e1 <ByteArray[268]>
[generated bytecode for function: setHasRejectionToWarn (0x143d9dd09c39 <SharedFunctionInfo setHasRejectionToWarn>)]
Bytecode length: 25
Parameter count 2
Register count 2
Frame size 16
Bytecode age: 0
 2193 S> 0xaa79bf233ee @    0 : 17 09             LdaImmutableCurrentContextSlot [9]
         0xaa79bf233f0 @    2 : aa 00             ThrowReferenceErrorIfHole [0]
         0xaa79bf233f2 @    4 : c4                Star0
         0xaa79bf233f3 @    5 : 17 17             LdaImmutableCurrentContextSlot [23]
 2202 E> 0xaa79bf233f5 @    7 : aa 01             ThrowReferenceErrorIfHole [1]
         0xaa79bf233f7 @    9 : c3                Star1
         0xaa79bf233f8 @   10 : 0b 03             Ldar a0
 2225 E> 0xaa79bf233fa @   12 : 97 06             JumpIfToBooleanFalse [6] (0xaa79bf23400 @ 18)
         0xaa79bf233fc @   14 : 0d 01             LdaSmi [1]
         0xaa79bf233fe @   16 : 8a 03             Jump [3] (0xaa79bf23401 @ 19)
         0xaa79bf23400 @   18 : 0c                LdaZero
 2223 E> 0xaa79bf23401 @   19 : 34 fa f9 00       SetKeyedProperty r0, r1, [0]
         0xaa79bf23405 @   23 : 0e                LdaUndefined
 2240 S> 0xaa79bf23406 @   24 : a9                Return
Constant pool (size = 2)
0xaa79bf23399: [FixedArray] in OldSpace
 - map: 0x3fc2dc0012d9 <Map(FIXED_ARRAY_TYPE)>
 - length: 2
           0: 0x04e986dc9919 <String[8]: #tickInfo>
           1: 0x04e986dc9cf1 <String[19]: #kHasRejectionToWarn>
Handler Table (size = 0)
Source Position Table (size = 13)
0x0aa79bf23409 <ByteArray[13]>
[generated bytecode for function: get (0x16e16e08b6e9 <SharedFunctionInfo get>)]
Bytecode length: 5
Parameter count 1
Register count 0
Frame size 0
Bytecode age: 0
 4174 S> 0xaa79bf234de @    0 : 16 03             LdaCurrentContextSlot [3]
         0xaa79bf234e0 @    2 : aa 00             ThrowReferenceErrorIfHole [0]
 4190 S> 0xaa79bf234e2 @    4 : a9                Return
Constant pool (size = 1)
0xaa79bf23491: [FixedArray] in OldSpace
 - map: 0x3fc2dc0012d9 <Map(FIXED_ARRAY_TYPE)>
 - length: 1
           0: 0x04e986dc2779 <String[8]: #exitCode>
Handler Table (size = 0)
Source Position Table (size = 8)
0x0aa79bf234e9 <ByteArray[8]>

*/